info:
    name: Default
    description: Default frontend theme for QuickApps
    version: 1.0
    author: Christopher Castro <y2k2000@gmail.com>

stylesheets:
    all: [reset.css, styles.css]

regions:
    language-switcher: Language Switcher
    search: Search form
    main-menu: Main menu
    user-menu: User menu
    
    slider: Slider
    content: Content
    footer: Footer
    
    services-left: Services Left
    services-center: Services Center
    services-right: Services Right
    
    sidebar-left: Sidebar Left
layout: default    